### PR TITLE
feat: add userController.getUserFollowings & Followers

### PR DESCRIPTION
**Pull request by rubylo718**
as title

### CODE REVIEW

**Comment by rubylo718** [comment]
[GET /api/users/:id/followings](https://trello.com/c/xmVXTxvY/56-get-api-users-id-followings)

**Comment by rubylo718** [comment]
also add getUserFollowers in userController which is similar with getUserFollowings

**Comment by rubylo718** [comment]
[GET /api/users/:id/followers](https://trello.com/c/7slt3zsr/57-get-api-users-id-followers)

**Review by ritachien — APPROVED** [review]
能產出正確資料!
這兩個 feature 看起來用了很多 `sequelize.literal()`， 感覺還有可以優化的地方! 但我們目前先以完成所有指定功能為首要目的，所以先通過 PR ，之後再來進行優化。

**Pull request merged**
