### PR TITLE
Feat/tweets: add 

### PR DESCRIPTION
**Pull request by rubylo718**
1. add GET /api/tweets
2. add tweets seeder

### CODE REVIEW

**Comment by rubylo718** [comment]
[新增 Tweet 種子資料](https://trello.com/c/A59U4rbg/17-%E6%96%B0%E5%A2%9E-tweet-%E7%A8%AE%E5%AD%90%E8%B3%87%E6%96%99)

**Comment by ritachien** [comment]
Ramdom recent date looks good! But it caused another problem -- tweets are created earlier than user. I'll fix user seeder in my next PR.

Do you think we should reset the seed records' ID numbers if seeders are undid? If yes, add in this PR. If no, I'll merge directly.
```js
down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('Tweets', {}, { truncate: true })
}
```

**Comment by rubylo718** [comment]
Good idea. Added. Thanks!

**Review by ritachien — APPROVED** [review]
Looks good!

**Pull request merged**
